# Configuration for move-issues - https://github.com/dessant/move-issues

# Delete the command comment. Ignored when the comment also contains other content
deleteCommand: true
# Close the source issue after moving
closeSourceIssue: true
# Lock the source issue after moving
lockSourceIssue: false
# Set custom aliases for targets
aliases:
  core: openhab-core
  addons: openhab-addons
  distro: openhab-distro
  docs: openhab-docs
  website: website
  android: openhab-android
  ios: openhab-ios
  zwave: org.openhab.binding.zwave
  zigbee: org.openhab.binding.zigbee
  openhabian: openhabian
  docker: openhab-docker
  linuxpkg: openhab-linuxpkg
  snap: openhab-snap
  vscode: openhab-vscode
